title: Just another blog
theme: jekyll-theme-tactile
author: Gabriel Fernandes Silva
email: ga3riel.fernandess@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing about what I`ve Learned...

# social links
twitter_username: your-twitter-handle
github_username:  gabifs

show_excerpts: true # set to false to remove excerpts on the homepage
